[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
python_files = "*_tests.py"
minversion = "7.0"
testpaths = ["tests"]
